extend type Mutation {
  """
  ✨ Insert a single `AcademicRecord` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  academicRecord_insert(
    """
    Data object to insert into the table.
    """
    data: AcademicRecord_Data!
  ): AcademicRecord_KeyOutput! @fdc_generated(from: "AcademicRecord", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ColumnMapping` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  columnMapping_insert(
    """
    Data object to insert into the table.
    """
    data: ColumnMapping_Data!
  ): ColumnMapping_KeyOutput! @fdc_generated(from: "ColumnMapping", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Enrollment` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  enrollment_insert(
    """
    Data object to insert into the table.
    """
    data: Enrollment_Data!
  ): Enrollment_KeyOutput! @fdc_generated(from: "Enrollment", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ImportLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  importLog_insert(
    """
    Data object to insert into the table.
    """
    data: ImportLog_Data!
  ): ImportLog_KeyOutput! @fdc_generated(from: "ImportLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ImportPreviewRow` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  importPreviewRow_insert(
    """
    Data object to insert into the table.
    """
    data: ImportPreviewRow_Data!
  ): ImportPreviewRow_KeyOutput! @fdc_generated(from: "ImportPreviewRow", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Quarter` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  quarter_insert(
    """
    Data object to insert into the table.
    """
    data: Quarter_Data!
  ): Quarter_KeyOutput! @fdc_generated(from: "Quarter", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `School` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  school_insert(
    """
    Data object to insert into the table.
    """
    data: School_Data!
  ): School_KeyOutput! @fdc_generated(from: "School", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SchoolYear` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  schoolYear_insert(
    """
    Data object to insert into the table.
    """
    data: SchoolYear_Data!
  ): SchoolYear_KeyOutput! @fdc_generated(from: "SchoolYear", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Section` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  section_insert(
    """
    Data object to insert into the table.
    """
    data: Section_Data!
  ): Section_KeyOutput! @fdc_generated(from: "Section", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SectionSubject` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sectionSubject_insert(
    """
    Data object to insert into the table.
    """
    data: SectionSubject_Data!
  ): SectionSubject_KeyOutput! @fdc_generated(from: "SectionSubject", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Student` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  student_insert(
    """
    Data object to insert into the table.
    """
    data: Student_Data!
  ): Student_KeyOutput! @fdc_generated(from: "Student", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Subject` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  subject_insert(
    """
    Data object to insert into the table.
    """
    data: Subject_Data!
  ): Subject_KeyOutput! @fdc_generated(from: "Subject", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SubjectGrade` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  subjectGrade_insert(
    """
    Data object to insert into the table.
    """
    data: SubjectGrade_Data!
  ): SubjectGrade_KeyOutput! @fdc_generated(from: "SubjectGrade", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Teacher` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  teacher_insert(
    """
    Data object to insert into the table.
    """
    data: Teacher_Data!
  ): Teacher_KeyOutput! @fdc_generated(from: "Teacher", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `TranscriptHeader` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  transcriptHeader_insert(
    """
    Data object to insert into the table.
    """
    data: TranscriptHeader_Data!
  ): TranscriptHeader_KeyOutput! @fdc_generated(from: "TranscriptHeader", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `TranscriptRemedialRow` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  transcriptRemedialRow_insert(
    """
    Data object to insert into the table.
    """
    data: TranscriptRemedialRow_Data!
  ): TranscriptRemedialRow_KeyOutput! @fdc_generated(from: "TranscriptRemedialRow", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `TranscriptSubjectRow` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  transcriptSubjectRow_insert(
    """
    Data object to insert into the table.
    """
    data: TranscriptSubjectRow_Data!
  ): TranscriptSubjectRow_KeyOutput! @fdc_generated(from: "TranscriptSubjectRow", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ValidationError` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  validationError_insert(
    """
    Data object to insert into the table.
    """
    data: ValidationError_Data!
  ): ValidationError_KeyOutput! @fdc_generated(from: "ValidationError", purpose: INSERT_SINGLE)
  """
  ✨ Insert `AcademicRecord` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  academicRecord_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [AcademicRecord_Data!]!
  ): [AcademicRecord_KeyOutput!]! @fdc_generated(from: "AcademicRecord", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ColumnMapping` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  columnMapping_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ColumnMapping_Data!]!
  ): [ColumnMapping_KeyOutput!]! @fdc_generated(from: "ColumnMapping", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Enrollment` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  enrollment_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Enrollment_Data!]!
  ): [Enrollment_KeyOutput!]! @fdc_generated(from: "Enrollment", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ImportLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  importLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ImportLog_Data!]!
  ): [ImportLog_KeyOutput!]! @fdc_generated(from: "ImportLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ImportPreviewRow` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  importPreviewRow_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ImportPreviewRow_Data!]!
  ): [ImportPreviewRow_KeyOutput!]! @fdc_generated(from: "ImportPreviewRow", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Quarter` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  quarter_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Quarter_Data!]!
  ): [Quarter_KeyOutput!]! @fdc_generated(from: "Quarter", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `School` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  school_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [School_Data!]!
  ): [School_KeyOutput!]! @fdc_generated(from: "School", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SchoolYear` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  schoolYear_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SchoolYear_Data!]!
  ): [SchoolYear_KeyOutput!]! @fdc_generated(from: "SchoolYear", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Section` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  section_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Section_Data!]!
  ): [Section_KeyOutput!]! @fdc_generated(from: "Section", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SectionSubject` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sectionSubject_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SectionSubject_Data!]!
  ): [SectionSubject_KeyOutput!]! @fdc_generated(from: "SectionSubject", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Student` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  student_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Student_Data!]!
  ): [Student_KeyOutput!]! @fdc_generated(from: "Student", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Subject` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  subject_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Subject_Data!]!
  ): [Subject_KeyOutput!]! @fdc_generated(from: "Subject", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SubjectGrade` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  subjectGrade_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SubjectGrade_Data!]!
  ): [SubjectGrade_KeyOutput!]! @fdc_generated(from: "SubjectGrade", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Teacher` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  teacher_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Teacher_Data!]!
  ): [Teacher_KeyOutput!]! @fdc_generated(from: "Teacher", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `TranscriptHeader` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  transcriptHeader_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [TranscriptHeader_Data!]!
  ): [TranscriptHeader_KeyOutput!]! @fdc_generated(from: "TranscriptHeader", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `TranscriptRemedialRow` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  transcriptRemedialRow_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [TranscriptRemedialRow_Data!]!
  ): [TranscriptRemedialRow_KeyOutput!]! @fdc_generated(from: "TranscriptRemedialRow", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `TranscriptSubjectRow` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  transcriptSubjectRow_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [TranscriptSubjectRow_Data!]!
  ): [TranscriptSubjectRow_KeyOutput!]! @fdc_generated(from: "TranscriptSubjectRow", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ValidationError` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  validationError_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ValidationError_Data!]!
  ): [ValidationError_KeyOutput!]! @fdc_generated(from: "ValidationError", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `AcademicRecord` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AcademicRecord`.
  """
  academicRecord_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: AcademicRecord_Data!
  ): AcademicRecord_KeyOutput! @fdc_generated(from: "AcademicRecord", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ColumnMapping` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ColumnMapping`.
  """
  columnMapping_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ColumnMapping_Data!
  ): ColumnMapping_KeyOutput! @fdc_generated(from: "ColumnMapping", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Enrollment` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Enrollment`.
  """
  enrollment_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Enrollment_Data!
  ): Enrollment_KeyOutput! @fdc_generated(from: "Enrollment", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ImportLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ImportLog`.
  """
  importLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ImportLog_Data!
  ): ImportLog_KeyOutput! @fdc_generated(from: "ImportLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ImportPreviewRow` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ImportPreviewRow`.
  """
  importPreviewRow_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ImportPreviewRow_Data!
  ): ImportPreviewRow_KeyOutput! @fdc_generated(from: "ImportPreviewRow", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Quarter` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Quarter`.
  """
  quarter_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Quarter_Data!
  ): Quarter_KeyOutput! @fdc_generated(from: "Quarter", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `School` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `School`.
  """
  school_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: School_Data!
  ): School_KeyOutput! @fdc_generated(from: "School", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SchoolYear` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SchoolYear`.
  """
  schoolYear_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SchoolYear_Data!
  ): SchoolYear_KeyOutput! @fdc_generated(from: "SchoolYear", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Section` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Section`.
  """
  section_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Section_Data!
  ): Section_KeyOutput! @fdc_generated(from: "Section", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SectionSubject` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SectionSubject`.
  """
  sectionSubject_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SectionSubject_Data!
  ): SectionSubject_KeyOutput! @fdc_generated(from: "SectionSubject", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Student` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Student`.
  """
  student_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Student_Data!
  ): Student_KeyOutput! @fdc_generated(from: "Student", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Subject` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Subject`.
  """
  subject_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Subject_Data!
  ): Subject_KeyOutput! @fdc_generated(from: "Subject", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SubjectGrade` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SubjectGrade`.
  """
  subjectGrade_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SubjectGrade_Data!
  ): SubjectGrade_KeyOutput! @fdc_generated(from: "SubjectGrade", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Teacher` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Teacher`.
  """
  teacher_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Teacher_Data!
  ): Teacher_KeyOutput! @fdc_generated(from: "Teacher", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `TranscriptHeader` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TranscriptHeader`.
  """
  transcriptHeader_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: TranscriptHeader_Data!
  ): TranscriptHeader_KeyOutput! @fdc_generated(from: "TranscriptHeader", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `TranscriptRemedialRow` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TranscriptRemedialRow`.
  """
  transcriptRemedialRow_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: TranscriptRemedialRow_Data!
  ): TranscriptRemedialRow_KeyOutput! @fdc_generated(from: "TranscriptRemedialRow", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `TranscriptSubjectRow` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TranscriptSubjectRow`.
  """
  transcriptSubjectRow_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: TranscriptSubjectRow_Data!
  ): TranscriptSubjectRow_KeyOutput! @fdc_generated(from: "TranscriptSubjectRow", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ValidationError` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ValidationError`.
  """
  validationError_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ValidationError_Data!
  ): ValidationError_KeyOutput! @fdc_generated(from: "ValidationError", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `AcademicRecord` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AcademicRecord`.
  """
  academicRecord_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [AcademicRecord_Data!]!
  ): [AcademicRecord_KeyOutput!]! @fdc_generated(from: "AcademicRecord", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ColumnMapping` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ColumnMapping`.
  """
  columnMapping_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ColumnMapping_Data!]!
  ): [ColumnMapping_KeyOutput!]! @fdc_generated(from: "ColumnMapping", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Enrollment` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Enrollment`.
  """
  enrollment_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Enrollment_Data!]!
  ): [Enrollment_KeyOutput!]! @fdc_generated(from: "Enrollment", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ImportLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ImportLog`.
  """
  importLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ImportLog_Data!]!
  ): [ImportLog_KeyOutput!]! @fdc_generated(from: "ImportLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ImportPreviewRow` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ImportPreviewRow`.
  """
  importPreviewRow_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ImportPreviewRow_Data!]!
  ): [ImportPreviewRow_KeyOutput!]! @fdc_generated(from: "ImportPreviewRow", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Quarter` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Quarter`.
  """
  quarter_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Quarter_Data!]!
  ): [Quarter_KeyOutput!]! @fdc_generated(from: "Quarter", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `School` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `School`.
  """
  school_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [School_Data!]!
  ): [School_KeyOutput!]! @fdc_generated(from: "School", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SchoolYear` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SchoolYear`.
  """
  schoolYear_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SchoolYear_Data!]!
  ): [SchoolYear_KeyOutput!]! @fdc_generated(from: "SchoolYear", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Section` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Section`.
  """
  section_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Section_Data!]!
  ): [Section_KeyOutput!]! @fdc_generated(from: "Section", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SectionSubject` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SectionSubject`.
  """
  sectionSubject_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SectionSubject_Data!]!
  ): [SectionSubject_KeyOutput!]! @fdc_generated(from: "SectionSubject", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Student` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Student`.
  """
  student_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Student_Data!]!
  ): [Student_KeyOutput!]! @fdc_generated(from: "Student", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Subject` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Subject`.
  """
  subject_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Subject_Data!]!
  ): [Subject_KeyOutput!]! @fdc_generated(from: "Subject", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SubjectGrade` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SubjectGrade`.
  """
  subjectGrade_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SubjectGrade_Data!]!
  ): [SubjectGrade_KeyOutput!]! @fdc_generated(from: "SubjectGrade", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Teacher` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Teacher`.
  """
  teacher_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Teacher_Data!]!
  ): [Teacher_KeyOutput!]! @fdc_generated(from: "Teacher", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `TranscriptHeader` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TranscriptHeader`.
  """
  transcriptHeader_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [TranscriptHeader_Data!]!
  ): [TranscriptHeader_KeyOutput!]! @fdc_generated(from: "TranscriptHeader", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `TranscriptRemedialRow` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TranscriptRemedialRow`.
  """
  transcriptRemedialRow_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [TranscriptRemedialRow_Data!]!
  ): [TranscriptRemedialRow_KeyOutput!]! @fdc_generated(from: "TranscriptRemedialRow", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `TranscriptSubjectRow` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TranscriptSubjectRow`.
  """
  transcriptSubjectRow_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [TranscriptSubjectRow_Data!]!
  ): [TranscriptSubjectRow_KeyOutput!]! @fdc_generated(from: "TranscriptSubjectRow", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ValidationError` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ValidationError`.
  """
  validationError_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ValidationError_Data!]!
  ): [ValidationError_KeyOutput!]! @fdc_generated(from: "ValidationError", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `AcademicRecord` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `AcademicRecord` or `null` if not found.
  """
  academicRecord_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AcademicRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AcademicRecord_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: AcademicRecord_Data!
  ): AcademicRecord_KeyOutput @fdc_generated(from: "AcademicRecord", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ColumnMapping` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ColumnMapping` or `null` if not found.
  """
  columnMapping_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ColumnMapping_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ColumnMapping_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ColumnMapping_Data!
  ): ColumnMapping_KeyOutput @fdc_generated(from: "ColumnMapping", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Enrollment` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Enrollment` or `null` if not found.
  """
  enrollment_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Enrollment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Enrollment_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Enrollment_Data!
  ): Enrollment_KeyOutput @fdc_generated(from: "Enrollment", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ImportLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ImportLog` or `null` if not found.
  """
  importLog_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ImportLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ImportLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ImportLog_Data!
  ): ImportLog_KeyOutput @fdc_generated(from: "ImportLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ImportPreviewRow` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ImportPreviewRow` or `null` if not found.
  """
  importPreviewRow_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ImportPreviewRow_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ImportPreviewRow_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ImportPreviewRow_Data!
  ): ImportPreviewRow_KeyOutput @fdc_generated(from: "ImportPreviewRow", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Quarter` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Quarter` or `null` if not found.
  """
  quarter_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Quarter_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Quarter_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Quarter_Data!
  ): Quarter_KeyOutput @fdc_generated(from: "Quarter", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `School` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `School` or `null` if not found.
  """
  school_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: School_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: School_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: School_Data!
  ): School_KeyOutput @fdc_generated(from: "School", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SchoolYear` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SchoolYear` or `null` if not found.
  """
  schoolYear_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SchoolYear_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SchoolYear_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SchoolYear_Data!
  ): SchoolYear_KeyOutput @fdc_generated(from: "SchoolYear", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Section` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Section` or `null` if not found.
  """
  section_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Section_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Section_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Section_Data!
  ): Section_KeyOutput @fdc_generated(from: "Section", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SectionSubject` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SectionSubject` or `null` if not found.
  """
  sectionSubject_update(
    """
    The key used to identify the object.
    """
    key: SectionSubject_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SectionSubject_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SectionSubject_Data!
  ): SectionSubject_KeyOutput @fdc_generated(from: "SectionSubject", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Student` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Student` or `null` if not found.
  """
  student_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Student_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Student_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Student_Data!
  ): Student_KeyOutput @fdc_generated(from: "Student", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Subject` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Subject` or `null` if not found.
  """
  subject_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Subject_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Subject_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Subject_Data!
  ): Subject_KeyOutput @fdc_generated(from: "Subject", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SubjectGrade` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SubjectGrade` or `null` if not found.
  """
  subjectGrade_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SubjectGrade_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SubjectGrade_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SubjectGrade_Data!
  ): SubjectGrade_KeyOutput @fdc_generated(from: "SubjectGrade", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Teacher` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Teacher` or `null` if not found.
  """
  teacher_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Teacher_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Teacher_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Teacher_Data!
  ): Teacher_KeyOutput @fdc_generated(from: "Teacher", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `TranscriptHeader` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `TranscriptHeader` or `null` if not found.
  """
  transcriptHeader_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TranscriptHeader_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TranscriptHeader_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: TranscriptHeader_Data!
  ): TranscriptHeader_KeyOutput @fdc_generated(from: "TranscriptHeader", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `TranscriptRemedialRow` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `TranscriptRemedialRow` or `null` if not found.
  """
  transcriptRemedialRow_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TranscriptRemedialRow_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TranscriptRemedialRow_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: TranscriptRemedialRow_Data!
  ): TranscriptRemedialRow_KeyOutput @fdc_generated(from: "TranscriptRemedialRow", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `TranscriptSubjectRow` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `TranscriptSubjectRow` or `null` if not found.
  """
  transcriptSubjectRow_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TranscriptSubjectRow_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TranscriptSubjectRow_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: TranscriptSubjectRow_Data!
  ): TranscriptSubjectRow_KeyOutput @fdc_generated(from: "TranscriptSubjectRow", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ValidationError` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ValidationError` or `null` if not found.
  """
  validationError_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ValidationError_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ValidationError_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ValidationError_Data!
  ): ValidationError_KeyOutput @fdc_generated(from: "ValidationError", purpose: UPDATE_SINGLE)
  """
  ✨ Update `AcademicRecord` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  academicRecord_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: AcademicRecord_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: AcademicRecord_Data!
  ): Int! @fdc_generated(from: "AcademicRecord", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ColumnMapping` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  columnMapping_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ColumnMapping_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ColumnMapping_Data!
  ): Int! @fdc_generated(from: "ColumnMapping", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Enrollment` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  enrollment_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Enrollment_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Enrollment_Data!
  ): Int! @fdc_generated(from: "Enrollment", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ImportLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  importLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ImportLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ImportLog_Data!
  ): Int! @fdc_generated(from: "ImportLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ImportPreviewRow` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  importPreviewRow_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ImportPreviewRow_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ImportPreviewRow_Data!
  ): Int! @fdc_generated(from: "ImportPreviewRow", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Quarter` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  quarter_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Quarter_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Quarter_Data!
  ): Int! @fdc_generated(from: "Quarter", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `School` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  school_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: School_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: School_Data!
  ): Int! @fdc_generated(from: "School", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SchoolYear` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  schoolYear_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SchoolYear_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SchoolYear_Data!
  ): Int! @fdc_generated(from: "SchoolYear", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Section` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  section_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Section_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Section_Data!
  ): Int! @fdc_generated(from: "Section", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SectionSubject` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  sectionSubject_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SectionSubject_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SectionSubject_Data!
  ): Int! @fdc_generated(from: "SectionSubject", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Student` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  student_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Student_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Student_Data!
  ): Int! @fdc_generated(from: "Student", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Subject` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  subject_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Subject_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Subject_Data!
  ): Int! @fdc_generated(from: "Subject", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SubjectGrade` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  subjectGrade_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SubjectGrade_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SubjectGrade_Data!
  ): Int! @fdc_generated(from: "SubjectGrade", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Teacher` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  teacher_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Teacher_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Teacher_Data!
  ): Int! @fdc_generated(from: "Teacher", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `TranscriptHeader` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  transcriptHeader_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: TranscriptHeader_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: TranscriptHeader_Data!
  ): Int! @fdc_generated(from: "TranscriptHeader", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `TranscriptRemedialRow` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  transcriptRemedialRow_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: TranscriptRemedialRow_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: TranscriptRemedialRow_Data!
  ): Int! @fdc_generated(from: "TranscriptRemedialRow", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `TranscriptSubjectRow` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  transcriptSubjectRow_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: TranscriptSubjectRow_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: TranscriptSubjectRow_Data!
  ): Int! @fdc_generated(from: "TranscriptSubjectRow", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ValidationError` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  validationError_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ValidationError_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ValidationError_Data!
  ): Int! @fdc_generated(from: "ValidationError", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `AcademicRecord` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  academicRecord_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AcademicRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AcademicRecord_FirstRow
  ): AcademicRecord_KeyOutput @fdc_generated(from: "AcademicRecord", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ColumnMapping` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  columnMapping_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ColumnMapping_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ColumnMapping_FirstRow
  ): ColumnMapping_KeyOutput @fdc_generated(from: "ColumnMapping", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Enrollment` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  enrollment_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Enrollment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Enrollment_FirstRow
  ): Enrollment_KeyOutput @fdc_generated(from: "Enrollment", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ImportLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  importLog_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ImportLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ImportLog_FirstRow
  ): ImportLog_KeyOutput @fdc_generated(from: "ImportLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ImportPreviewRow` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  importPreviewRow_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ImportPreviewRow_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ImportPreviewRow_FirstRow
  ): ImportPreviewRow_KeyOutput @fdc_generated(from: "ImportPreviewRow", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Quarter` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  quarter_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Quarter_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Quarter_FirstRow
  ): Quarter_KeyOutput @fdc_generated(from: "Quarter", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `School` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  school_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: School_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: School_FirstRow
  ): School_KeyOutput @fdc_generated(from: "School", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SchoolYear` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  schoolYear_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SchoolYear_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SchoolYear_FirstRow
  ): SchoolYear_KeyOutput @fdc_generated(from: "SchoolYear", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Section` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  section_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Section_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Section_FirstRow
  ): Section_KeyOutput @fdc_generated(from: "Section", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SectionSubject` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  sectionSubject_delete(
    """
    The key used to identify the object.
    """
    key: SectionSubject_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SectionSubject_FirstRow
  ): SectionSubject_KeyOutput @fdc_generated(from: "SectionSubject", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Student` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  student_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Student_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Student_FirstRow
  ): Student_KeyOutput @fdc_generated(from: "Student", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Subject` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  subject_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Subject_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Subject_FirstRow
  ): Subject_KeyOutput @fdc_generated(from: "Subject", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SubjectGrade` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  subjectGrade_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SubjectGrade_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SubjectGrade_FirstRow
  ): SubjectGrade_KeyOutput @fdc_generated(from: "SubjectGrade", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Teacher` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  teacher_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Teacher_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Teacher_FirstRow
  ): Teacher_KeyOutput @fdc_generated(from: "Teacher", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `TranscriptHeader` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  transcriptHeader_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TranscriptHeader_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TranscriptHeader_FirstRow
  ): TranscriptHeader_KeyOutput @fdc_generated(from: "TranscriptHeader", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `TranscriptRemedialRow` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  transcriptRemedialRow_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TranscriptRemedialRow_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TranscriptRemedialRow_FirstRow
  ): TranscriptRemedialRow_KeyOutput @fdc_generated(from: "TranscriptRemedialRow", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `TranscriptSubjectRow` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  transcriptSubjectRow_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TranscriptSubjectRow_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TranscriptSubjectRow_FirstRow
  ): TranscriptSubjectRow_KeyOutput @fdc_generated(from: "TranscriptSubjectRow", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ValidationError` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  validationError_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ValidationError_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ValidationError_FirstRow
  ): ValidationError_KeyOutput @fdc_generated(from: "ValidationError", purpose: DELETE_SINGLE)
  """
  ✨ Delete `AcademicRecord` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  academicRecord_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: AcademicRecord_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "AcademicRecord", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ColumnMapping` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  columnMapping_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ColumnMapping_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ColumnMapping", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Enrollment` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  enrollment_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Enrollment_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Enrollment", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ImportLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  importLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ImportLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ImportLog", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ImportPreviewRow` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  importPreviewRow_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ImportPreviewRow_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ImportPreviewRow", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Quarter` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  quarter_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Quarter_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Quarter", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `School` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  school_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: School_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "School", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SchoolYear` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  schoolYear_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SchoolYear_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SchoolYear", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Section` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  section_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Section_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Section", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SectionSubject` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  sectionSubject_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SectionSubject_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SectionSubject", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Student` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  student_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Student_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Student", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Subject` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  subject_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Subject_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Subject", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SubjectGrade` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  subjectGrade_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SubjectGrade_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SubjectGrade", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Teacher` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  teacher_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Teacher_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Teacher", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `TranscriptHeader` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  transcriptHeader_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: TranscriptHeader_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "TranscriptHeader", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `TranscriptRemedialRow` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  transcriptRemedialRow_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: TranscriptRemedialRow_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "TranscriptRemedialRow", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `TranscriptSubjectRow` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  transcriptSubjectRow_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: TranscriptSubjectRow_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "TranscriptSubjectRow", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ValidationError` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  validationError_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ValidationError_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ValidationError", purpose: DELETE_MULTIPLE)
}
